[buildPlans.iosevka-habamax]
family      = "Iosevka Habamax"
spacing     = "term"
no-cv-ss    = true
no-ligation = true
serifs      = "sans"


[buildPlans.iosevka-habamax.variants.design]
three     = 'flattop'
four      = 'open-non-crossing'
asterisk  = 'hex-low'
bar       = 'force-upright'
percent   = 'rings-continuous-slash'


[buildPlans.iosevka-habamax.variants.italic]
k = 'straight-serifless'


[buildPlans.iosevka-habamax.weights.regular]
shape = 400  # Weight for glyph shapes
menu  = 400  # Weight for menu name
css   = 400  # Weight for webfont CSS


[buildPlans.iosevka-habamax.weights.bold]
shape = 700
menu  = 700
css   = 700


[buildPlans.iosevka-habamax.slopes]
upright = "normal"
italic  = "italic"


[buildPlans.iosevka-habamax.widths.normal]
shape = 600
menu  = 5
css   = "normal"
